-- 04_set_memory_parameters.sql

ALTER SYSTEM SET SGA_TARGET = 1G SCOPE = SPFILE;
ALTER SYSTEM SET SGA_MAX_SIZE = 1G SCOPE = SPFILE;
ALTER SYSTEM SET PGA_AGGREGATE_TARGET = 512M SCOPE = SPFILE;
ALTER SYSTEM SET PGA_AGGREGATE_LIMIT = 768M SCOPE = SPFILE;