-- 01_create_tables.sql
ALTER SESSION SET CONTAINER = mon_28028_herve_microloanApproval_db;

-- Borrowers table
CREATE TABLE borrowers (
    borrower_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    dob DATE,
    gender CHAR(1) CHECK (gender IN ('M','F')),
    phone VARCHAR2(20) UNIQUE,
    email VARCHAR2(100) UNIQUE,
    occupation VARCHAR2(100),
    income NUMBER(10,2),
    registration_date DATE DEFAULT SYSDATE
);

-- Loans table
CREATE TABLE loans (
    loan_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    borrower_id NUMBER NOT NULL,
    loan_amount NUMBER(12,2) NOT NULL,
    loan_term NUMBER(3) NOT NULL,
    interest_rate NUMBER(5,2) DEFAULT 5.0,
    loan_status VARCHAR2(20) DEFAULT 'Pending' CHECK (loan_status IN ('Pending','Approved','Rejected','Closed')),
    application_date DATE DEFAULT SYSDATE,
    FOREIGN KEY (borrower_id) REFERENCES borrowers(borrower_id)
);

-- Risk Evaluations table
CREATE TABLE risk_evaluations (
    risk_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    loan_id NUMBER NOT NULL,
    credit_score NUMBER(3) CHECK (credit_score BETWEEN 0 AND 850),
    risk_level VARCHAR2(20) CHECK (risk_level IN ('Low','Medium','High')),
    evaluation_date DATE DEFAULT SYSDATE,
    FOREIGN KEY (loan_id) REFERENCES loans(loan_id)
);

-- Payments table
CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    loan_id NUMBER NOT NULL,
    payment_date DATE DEFAULT SYSDATE,
    amount_paid NUMBER(12,2),
    payment_method VARCHAR2(50),
    FOREIGN KEY (loan_id) REFERENCES loans(loan_id)
);
